Repository ourownstory/neural_prophet, pull requests merged in 2022-10, with the labels that each got.

#733 TorchProphet
  neuralprophet/TorchProphet.py
  neuralprophet/__init__.py
  tests/test_wrapper.py
  tutorials/feature-use/Prophet_to_TorchProphet.ipynb
Labels: enhancement

#779 [feature] separate panel uncertainty plot
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast.py
  neuralprophet/plot_forecast_plotly.py
  tests/test_plotting.py
  tutorials/feature-use/plotly.ipynb
  tutorials/feature-use/uncertainty_estimation.ipynb
Labels: enhancement, uncertainty

#853 [feature] Support setting custom quantile in plot_parameters()
  neuralprophet/forecaster.py
  neuralprophet/plot_model_parameters.py
  neuralprophet/plot_model_parameters_plotly.py
  tests/test_plotting.py
Labels: enhancement, plot

#854 [refactor] TorchProphet
  neuralprophet/TorchProphet.py
  tests/test_wrapper.py
  tutorials/feature-use/Prophet_to_TorchProphet.ipynb
Labels: bug

#877 changed metrics target branch
  .github/workflows/metrics.yml
Labels: bug

#893 [bugfix] Added repository to metrics artifact download
  .github/workflows/metrics.yml
Labels: bug

#892 [lightning] Learning rate finder optimization
  neuralprophet/configure.py
  neuralprophet/forecaster.py
  neuralprophet/utils.py
Labels: model
