Repository ourownstory/neural_prophet, pull requests merged in 2022-12, with the labels that each got.

#1012 [website] Fix typo in preview of website description
  docs/source/_templates/index.html
Labels: status: ready

#1010 Move tensors to correct device
  neuralprophet/custom_loss_metrics.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
  tests/test_integration.py
Labels: bug, status: needs review

#997 Meta name bool
  neuralprophet/forecaster.py
  neuralprophet/time_net.py
Labels: status: ready

#802 Uncertainty: Conformal Prediction V1
  neuralprophet/configure.py
  neuralprophet/conformal_prediction.py
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_forecast_plotly.py
  scripts/pre_commit.bash
  tests/test_plotting.py
  tests/test_uncertainty.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
  tutorials/feature-use/uncertainty_estimation.ipynb
Labels: enhancement, model, uncertainty, status: needs review

#1006 Change plotting_backend deprecation warning for implicit and explicit matplotlib use
  neuralprophet/forecaster.py
  neuralprophet/plot_utils.py
Labels: plotting, status: ready, refactoring

#974 [feature] Add a main script to print neuralprophet version
  neuralprophet/__main__.py
  tests/test_cli.py
Labels: status: ready

#902 [dev-ops] Type annotation validation GitHub action
  .github/workflows/linters.yml
  pyproject.toml
  requirements/dev.txt
Labels: status: ready

#915 Add pull request template for Github
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, status: needs attention

#1023 Follow-up tensors on wrong device
  neuralprophet/time_net.py
Labels: bug

#1024 Fix label links in contributing guidelines
  CONTRIBUTING.md
Labels: status: ready

#1022 [fix] Replace all deprecated plot_last_forecast with plot_latest_forecast
  tests/test_integration.py
  tests/test_uncertainty.py
  tutorials/feature-use/autoregression_yosemite_temps.ipynb
  tutorials/feature-use/uncertainty_estimation.ipynb
Labels: status: ready

#1021 [refactor] Rename config_seasonality and add typings
  neuralprophet/configure.py
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_matplotlib.py
  neuralprophet/plot_model_parameters_plotly.py
  neuralprophet/plot_utils.py
  neuralprophet/time_dataset.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
  tests/test_glocal.py
  tests/test_integration.py
Labels: status: ready

#1020 [refactor] Remove duplicate season reg lambda
  neuralprophet/configure.py
  neuralprophet/forecaster.py
  neuralprophet/time_net.py
Labels: status: ready

#1035 [fix] Renamed reamining self.config_season variables to self.config_seasonality in time_net.py
  neuralprophet/time_net.py
Labels: bug

#1032 Removed commented tests in test_uncertainty.py.
  tests/test_uncertainty.py
Labels: refactoring

#1041 Normalize training speed metric
  tests/test_model_performance.py
Labels: refactoring

#1043 Update metrics.yml
  .github/workflows/metrics.yml
Labels: enhancement

#1031 [devops] Cleanup and limit CodeQL Github action to main branch
  .github/workflows/codeql-analysis.yml
Labels: status: ready

#1001 Support for holidays of multiple countries
  neuralprophet/forecaster.py
  neuralprophet/time_dataset.py
  neuralprophet/utils.py
  tests/test_unit.py
Labels: enhancement, status: ready

#1040 Refactored dataloader
  neuralprophet/time_dataset.py
Labels: status: ready, refactoring

#1045 Normalize training time metric
  tests/metrics/compareMetrics.py
Labels: enhancement

#1044 Uncertainty: Conformal Prediction V2 - add .conformal_predict() and remove .conformalize() in forecaster.py
  neuralprophet/configure.py
  neuralprophet/forecaster.py
  tests/test_plotting.py
  tests/test_uncertainty.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
  tutorials/feature-use/uncertainty_quantile_regression.ipynb
Labels: enhancement, uncertainty, status: ready

#1039 Refactored fit() interface
  neuralprophet/configure.py
  neuralprophet/forecaster.py
  neuralprophet/logger.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
  neuralprophet/utils_metrics.py
  tests/test_model_performance.py
Labels: refactoring, status: needs review

#1064 [Fix] Fixed error in plot loss
  neuralprophet/forecaster.py
Labels: bug

#1075 Improve plotly interactive rendering performance
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_plotly.py
  tests/temp_plotly_performance.ipynb
  tests/temp_plotly_performance.py
  tests/test_plotting.py
Labels: enhancement, plotting, P2

#1080 Restict numpy version to <1.24.0
  requirements/base.txt
Labels: bug, status: needs review, P1

#1079 remove default settings (None for calibration df and 0.1 for alpha)
  neuralprophet/forecaster.py
Labels: enhancement, uncertainty, refactoring, status: needs review, P2

#1083 add plotly resampler
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_plotly.py
  requirements/base.txt
  tests/test_plotting.py
Labels: enhancement, plotting, status: ready
