Repository ourownstory/neural_prophet, pull requests merged in 2022-11, with the labels that each got.

#898 [fix] added kaleido dev requirement
  requirements/dev.txt
Labels: bug, status: ready

#908 [logging] display logs in console
  tests/__init__.py
  tests/pytest.ini
  tests/test_glocal.py
  tests/test_integration.py
  tests/test_model_performance.py
  tests/test_plotting.py
  tests/test_regularization.py
  tests/test_uncertainty.py
  tests/test_unit.py
  tests/test_utils.py
  tests/test_wrapper.py
Labels: enhancement, status: ready

#924 [refactor] Move requirements.txt into subfolder
  .github/workflows/ci.yml
  .github/workflows/website.yml
  MANIFEST.in
  requirements/base.txt
  setup.py
Labels: status: ready

#937 Clean up and remove some unused website files
  _site/html/index.html
  docs/.nojekyll
Labels: status: ready

#909 813 Remove regressor if training set has one unique value
  neuralprophet/df_utils.py
  neuralprophet/forecaster.py
  tests/test_integration.py
  tests/test_regularization.py
  tests/test_unit.py
Labels: enhancement, status: ready

#837 Lightning Migration
  .gitignore
  neuralprophet/configure.py
  neuralprophet/forecaster.py
  neuralprophet/logger.py
  neuralprophet/metrics.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
  neuralprophet/utils_torch.py
  requirements/base.txt
  tests/__init__.py
  tests/pytest.ini
  tests/test_integration.py
  tests/test_model_performance.py
  tests/test_utils.py
  tutorials/feature-use/network_architecture_visualization.ipynb
Labels: model, status: needs review

#952 [lightning] remove rich progress bar
  neuralprophet/utils.py
Labels: bug, status: needs review

#958 Added plot param of the NeuralProphet fit() and uncomment test_progress_display in test_integration.py.
  neuralprophet/forecaster.py
  tests/test_integration.py
Labels: tests, refactoring

#959 [lightning] refactored Trainer args
  neuralprophet/forecaster.py
  neuralprophet/utils.py
Labels: bug, status: needs review

#960 refactored test failure
  neuralprophet/forecaster.py
  tests/test_integration.py
Labels: bug, status: needs review

#929 Remove support for df dict as an input
  neuralprophet/df_utils.py
  neuralprophet/forecaster.py
  tests/test_integration.py
  tests/test_unit.py
Labels: enhancement, status: needs review

#919 Add alias function plot_last_forecast() for plot_latest_forecast() and give deprecation warning
  neuralprophet/forecaster.py
  tests/test_integration.py
Labels: bug, status: ready

#808 Mask seasonality on Sat/Sun when data frequency is Business days
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters.py
  neuralprophet/plot_model_parameters_plotly.py
  tests/test_integration.py
  tests/test_plotting.py
Labels: enhancement, plotting, status: needs review

#978 [bug] Forecast output dataframe contains all float dtypes instead of having some objects
  neuralprophet/forecaster.py
Labels: bug, good first issue, status: needs review

#942 Fix labels of yhatx and origin-x in plots
  neuralprophet/plot_forecast.py
  neuralprophet/plot_forecast_plotly.py
Labels: plotting, status: ready

#936 Improve github action speed for docs test
  .github/workflows/ci.yml
Labels: status: ready

#927 Remove residuals in forecast dataframe returned by m.predict()
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast.py
  neuralprophet/plot_forecast_plotly.py
  tests/test_plotting.py
Labels: enhancement, plotting, status: ready

#968 Resolved discontinuous trend when changepoints are not sorted chronologically
  neuralprophet/configure.py
Labels: bug, status: ready

#934 Address small tech debt to use a conditional instead of try/except for Python 3.7 support
  neuralprophet/forecaster.py
Labels: status: ready

#926 [dev-ops] Collapsible metrics reports
  .github/workflows/metrics.yml
Labels: status: needs review

#975 Cleanup document files
  docs/Makefile
  docs/source/_templates/sidebar/brand.html
  docs/source/contents.rst
  docs/source/model-overview.md
  docs/source/science-behind/model-overview.md
Labels: status: needs review

#971 Rename plot_forecast.py and plot_model_parameters.py to xxx_matplotli…
  docs/source/code/forecaster.rst
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_model_parameters_matplotlib.py
  neuralprophet/plot_model_parameters_plotly.py
Labels: refactoring, status: needs fix

#961 [lightning] GPU support
  neuralprophet/forecaster.py
  neuralprophet/utils.py
Labels: enhancement, compute, status: needs fix

#921 [naming] Renamed tutorial notebooks
  docs/source/notebooks/Prophet_to_TorchProphet.nblink
  docs/source/notebooks/prophet_to_torch_prophet.nblink
  neuralprophet/__init__.py
  neuralprophet/torch_prophet.py
  tutorials/feature-use/migration_from_prophet.ipynb
  tutorials/feature-use/prophet_to_torch_prophet.ipynb
Labels: refactoring, status: blocked

#884 [feature] Support plotting of only specific panels in plot_parameters and plot_components
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_matplotlib.py
  neuralprophet/plot_model_parameters_plotly.py
  tests/test_plotting.py
Labels: enhancement, plotting, status: ready

#946 Labels in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#914 [enhancement] add pytests for matplotlib
  tests/test_integration.py
  tests/test_plotting.py
  tests/test_uncertainty.py
Labels: enhancement, plotting, status: ready

#980 [devops] Improve codecov threshold
  codecov.yml
Labels: status: ready

#979 [devops] Upgrade GitHub action versions
  .github/workflows/ci.yml
  .github/workflows/linters.yml
  requirements/dev.txt
Labels: status: ready

#981 [typing] Add type annotations for main NeuralProphet class
  neuralprophet/configure.py
  neuralprophet/forecaster.py
  neuralprophet/np_types.py
  neuralprophet/utils.py
  tests/test_unit.py
Labels: status: ready

#984 change deprecation message to switch plotting backend to plotly
  neuralprophet/forecaster.py
Labels: plotting, status: ready

#888 [feature] Plot components of averaged df (and quants) if multiple IDs, but no df_name specified in plot_components()
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_matplotlib.py
  neuralprophet/plot_model_parameters_plotly.py
  tests/test_glocal.py
  tests/test_integration.py
  tests/test_plotting.py
Labels: enhancement, status: needs review

#990 [devops] Code coverage threshold fix
  codecov.yml
Labels: status: ready

#995 Time in model training benchmark
  .github/workflows/metrics.yml
  tests/test_model_performance.py
Labels: status: needs review

#994 Unified the naming of variables - num and nb
  neuralprophet/forecaster.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
  tests/test_glocal.py
Labels: status: ready

#983 [tests] Add tests for configure
  tests/test_configure.py
Labels: status: ready

#988 [cleanup] Remove unused from_kwargs config function
  neuralprophet/configure.py
Labels: status: ready

#986 [devops] Add shell script to setup basic development environment
  scripts/setup.sh
Labels: status: ready

#973 [lightning] Speed-up
  neuralprophet/__init__.py
  neuralprophet/forecaster.py
  neuralprophet/logger.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
Labels: status: ready

#1003 Update progress bar only every epoch
  neuralprophet/utils.py
Labels: status: ready, refactoring

#987 [typing] Resolve type annotation issues in configure file
  neuralprophet/configure.py
  neuralprophet/forecaster.py
Labels: status: needs review

#989 [typing] Add ConfigEvents type annotations
  neuralprophet/configure.py
  neuralprophet/df_utils.py
  neuralprophet/time_dataset.py
  neuralprophet/utils.py
Labels: status: ready

#1000 [refactor] Extract plot utils into dedicated file
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_matplotlib.py
  neuralprophet/plot_model_parameters_plotly.py
  neuralprophet/plot_utils.py
  neuralprophet/utils.py
Labels: plotting, status: ready, refactoring
