Repository ourownstory/neural_prophet, pull requests merged in 2023-02, with the labels that each got.

#1145 Lightning version
  requirements/base.txt
Labels: refactoring

#1110 Avoidance of duplicate code in regularisation
  neuralprophet/hdays.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_plotly.py
  neuralprophet/time_dataset.py
  neuralprophet/utils.py
  tests/test_unit.py
Labels: status: ready, refactoring

#1144 Future regressors modularization
  neuralprophet/components/README.md
  neuralprophet/components/future_regressors/__init__.py
  neuralprophet/components/future_regressors/future_regressors.py
  neuralprophet/components/future_regressors/linear.py
  neuralprophet/components/router.py
  neuralprophet/plot_utils.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
Labels: status: ready, modularity

#1146 Allow unique values for future regressor of one time series in global modeling
  neuralprophet/df_utils.py
Labels: status: needs update

#1122 Added ability to pass custom callbacks while adhering to callback con…
  neuralprophet/utils.py
Labels: status: ready, refactoring

#1116 Improve usability for conditional seasonality
  neuralprophet/__init__.py
  neuralprophet/df_utils.py
  neuralprophet/forecaster.py
  neuralprophet/time_dataset.py
  tests/test_integration.py
  tutorials/feature-use/conditional_seasonality_peyton.ipynb
Labels: status: ready

#1156 Fixed pyright error raised from unbound list
  neuralprophet/forecaster.py
Labels: bug, status: needs review

#1155 Uncertainty: Conformal Prediction V1.2 - move conformal evaluation performance metrics inside of Conformal class in conformal.py
  neuralprophet/conformal.py
  neuralprophet/forecaster.py
  tests/test_uncertainty.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: status: ready, refactoring, P2

#1085 [Minor] Convert timezones to UTC by default
  neuralprophet/df_utils.py
Labels: status: needs update, P3

#1128 [fix] default value of n_changepoints given correctly in the docs
  docs/source/guides/hyperparameter-selection.md
Labels: status: ready

#1174 [devops] Fixed pyright violation of seasonalities
  neuralprophet/time_net.py
Labels: task

#1105 [refactor] incorporate typing for time_net.py
  neuralprophet/time_net.py
Labels: P3

#1140 [docs] Readme library purpose
  README.md
Labels: docs, status: ready

#1175 [minor] Add get function for parameters
  neuralprophet/forecaster.py
Labels: status: needs review

#1148 [tests] Added info logs to regularisation tests
  tests/test_regularization.py
Labels: status: ready
