Repository ourownstory/neural_prophet, pull requests merged in 2023-03, with the labels that each got.

#1038 [feature] Customized forecast frequency
  neuralprophet/forecaster.py
  neuralprophet/time_dataset.py
  tests/test_integration.py
  tests/test_unit.py
Labels: status: needs review, P1

#1173 [minor] Refactored Learning Rate Finder
  neuralprophet/utils.py
Labels: status: ready, task

#1177 [fix] Fix pyright warnings on wrong types
  neuralprophet/forecaster.py
  neuralprophet/time_net.py
Labels: status: ready, P1

#1182 [docs] shorten contributing.md
  CONTRIBUTING.md
Labels: docs, status: needs review, P3

#1179 [refactor] Refactor the prep_or_copy_df method
  neuralprophet/df_utils.py
Labels: status: ready, P3

#1180 [refactor] Remove duplicate df_prep_or_copy call
  neuralprophet/forecaster.py
Labels: status: ready, P3

#1186 [devops] Downgrade python to 3.7 for pyright
  .github/workflows/linters.yml
  neuralprophet/df_utils.py
Labels: status: ready, P2

#1118 [docs] Revamp conformal prediction tutorial material
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: docs, status: ready, P3

#1192 [refactor] Uncertainty: Conformal Prediction V1.2 - Rerun uncertainty_conformal_prediction.ipynb
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: status: ready, P2

#1193 [typing] Add typing for user facing functions
  neuralprophet/configure.py
  neuralprophet/df_utils.py
  neuralprophet/forecaster.py
  neuralprophet/utils.py
Labels: status: needs review

#1203 [minor] Adjust seasonality reg to modularized code
  neuralprophet/time_net.py
Labels: bug

#1199 [docs] Style fixes in tutorial notebooks when dark mode is active
  docs/source/_static/css/custom.css
Labels: docs, status: needs review

#1210 [refactor] Move evaluate method outside of Conformal class and rename it as conformal_evaluate
  neuralprophet/__init__.py
  neuralprophet/conformal.py
  neuralprophet/forecaster.py
  tests/test_uncertainty.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: status: ready, status: needs review, P2

#1213 [Refactor] Renamed conformal.py to uncertainty.py and conformal_evalute() to uncertainty_evaluate().
  neuralprophet/__init__.py
  neuralprophet/forecaster.py
  neuralprophet/uncertainty.py
  tests/test_uncertainty.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: P2, status: draft

#1212 [refactor] Modified n_forecasts in _infer_evaluate_params_from_dataset() method in conformal.py
  tests/test_uncertainty.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: status: needs review, P2

#1214 [refactor] Add quantile regression (QR) as an uncertainty evalution metric in uncertainty.py
  neuralprophet/uncertainty.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: status: needs review, P2

#1206 [refactor] Renamed base components
  neuralprophet/components/future_regressors/__init__.py
  neuralprophet/components/future_regressors/base.py
  neuralprophet/components/seasonality/__init__.py
  neuralprophet/components/seasonality/base.py
  neuralprophet/components/trend/__init__.py
  neuralprophet/components/trend/base.py
Labels: task
