Repository ourownstory/neural_prophet, pull requests merged in 2023-04, with the labels that each got.

#1242 [docs] outdated labels in contributing.md
  CONTRIBUTING.md
Labels: docs, status: needs review

#1246 [refactor] Removed plotting in test_uncertainty.py.
  tests/test_uncertainty.py
Labels: status: ready, P2

#1248 [refactor] Changed int() to round() for q_hat_idx in uncertainty.py.
  neuralprophet/uncertainty.py
Labels: bug, P2

#1207 [tests] Remove unneeded logs
  tests/pytest.ini
  tests/test_integration.py
  tests/test_unit.py
Labels: task

#1215 [feature] Support for asymmetrical interval in conformal quantile regression
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/uncertainty.py
  tests/test_plotting.py
  tests/test_uncertainty.py
  tutorials/feature-use/conditional_seasonality_peyton.ipynb
Labels: status: ready

#1255 [refactor] Lighten forecaster.py
  neuralprophet/data/process.py
  neuralprophet/data/split.py
  neuralprophet/data/transform.py
  neuralprophet/forecaster.py
  tests/test_integration.py
  tests/test_unit.py
Labels: status: ready

#1256 [minor] Allow lagged regressors with only unique values for global modeling
  neuralprophet/df_utils.py
  tests/test_integration.py
Labels: status: needs update

#1254 [minor] Repeat static trend component n_forecasts times instead of only once
  neuralprophet/components/trend/static.py
Labels: status: needs review

#1268 [docs] add note on flexible multiplicativity from prophet
  docs/source/guides/changes-from-prophet.md
Labels: status: needs review

#1267 [minor] Allow lagged regressors with only unique values for global modeling
  neuralprophet/data/process.py
  neuralprophet/data/split.py
  neuralprophet/df_utils.py
  tests/test_integration.py
Labels: bug, status: ready

#1187 [major] Allow user to set prediction frequency as a dict: {freq: forecast origin}
  neuralprophet/data/process.py
  neuralprophet/df_utils.py
  neuralprophet/forecaster.py
  neuralprophet/time_dataset.py
  tests/test_integration.py
Labels: status: needs review, P1

#1202 [minor] Dependency management with poetry
  poetry.lock
  pyproject.toml
Labels: status: ready

#1276 [minor] Address warnings
  neuralprophet/data/process.py
Labels: status: needs review

#1278 [minor] lighten forecaster step 2 - encapsulate _get_maybe_extend_periods and _maybe_extend_df
  neuralprophet/data/split.py
  neuralprophet/forecaster.py
Labels: status: needs review

#1279 [refactor] Encapsulate _make_future_dataframe and _check_dataframe
  neuralprophet/data/process.py
  neuralprophet/data/split.py
  neuralprophet/forecaster.py
Labels: status: needs review

#1282 [fix] Raise Exception again to avoid UnboundLocalError
  neuralprophet/utils.py
Labels: status: ready

#1280 [minor] Update dependencies to latest versions
  poetry.lock
Labels: status: needs review

#1284 [docs] Improve conformal prediction tutorial by adding marginal before coverage
  docs/source/new-tutorials/tutorial08.ipynb
Labels: status: ready

#1216 [major] Nested Additive Model
  neuralprophet/components/seasonality/fourier.py
  neuralprophet/time_dataset.py
  neuralprophet/time_net.py
Labels: status: ready

#1289 [refactor] Encapsulate _validate_column_name
  neuralprophet/data/process.py
  neuralprophet/forecaster.py
  tests/test_integration.py
Labels: status: needs review

#1287 [refactor] Encapsulate _normalize
  neuralprophet/data/transform.py
  neuralprophet/forecaster.py
  tests/test_unit.py
Labels: status: needs review

#1288 [refactor] Encapsulate _handle_missing_data and _handle_missing_data_single_id
  neuralprophet/data/process.py
  neuralprophet/forecaster.py
  tests/test_integration.py
  tests/test_unit.py
Labels: status: needs review

#1290 [refactor] Encapsulate _prepare_dataframe_to_predict
  neuralprophet/data/process.py
  neuralprophet/forecaster.py
Labels: status: needs review

#1295 [minor] add docstring examples
  neuralprophet/utils.py
Labels: status: ready

#1298 [fix] Remove SmoothL1Loss from Tutorial
  neuralprophet/time_net.py
  tutorials/feature-use/test_and_crossvalidate.ipynb
Labels: bug, status: needs review

#1291 [refactor] Encapsulate _convert_raw_predictions_to_raw_df
  neuralprophet/data/process.py
  neuralprophet/forecaster.py
  neuralprophet/np_types.py
Labels: status: needs review

#1300 [fix] Raise ValueError when df contains not enough rows
  neuralprophet/data/process.py
  tests/test_integration.py
Labels: bug, status: needs review, P1

#1271 [major] Drop Python 3.7 support and complete poetry migration
  .github/workflows/ci.yml
  .github/workflows/linters.yml
  MANIFEST.in
  neuralprophet/forecaster.py
  poetry.lock
  pyproject.toml
  requirements/base.txt
  requirements/dev.txt
  requirements/docs.txt
Labels: status: needs review

#1225 Uncertainty quantification tutorial
  tutorials/feature-use/uncertainty_quantification.ipynb
Labels: docs, status: needs update, P2

#1286 [minor] Add static plotly backend
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/plot_model_parameters_plotly.py
  poetry.lock
  pyproject.toml
  tests/test_plotting.py
Labels: status: ready

#1309 [docs] Update documentation website
  docs/README.md
  docs/feature-guides-archive/autoregression_yosemite_temps.ipynb
  docs/feature-guides-archive/events_holidays_peyton_manning.ipynb
  docs/feature-guides-archive/global_modeling.ipynb
  docs/feature-guides-archive/lagged_covariates_energy_ercot.ipynb
  docs/feature-guides-archive/migration_from_prophet.ipynb
  docs/feature-guides-archive/prophet_to_torch_prophet.ipynb
  docs/feature-guides-archive/trend_peyton_manning.ipynb
  docs/source/how-to-guides/application-examples/energy_hospital_load.ipynb
  docs/source/how-to-guides/application-examples/energy_solar_pv.ipynb
  docs/source/how-to-guides/feature-guides/plotly.ipynb
  docs/source/how-to-guides/feature-guides/uncertainty_conformal_prediction.ipynb
  docs/source/how-to-guides/feature-guides/uncertainty_quantification.ipynb
  docs/source/how-to-guides/feature-guides/uncertainty_quantile_regression.ipynb
  docs/source/how-to-guides/index.rst
  docs/source/quickstart.md
  docs/source/tutorials/tutorial01.ipynb
  docs/source/tutorials/tutorial02.ipynb
  docs/source/tutorials/tutorial03.ipynb
  docs/source/tutorials/tutorial04.ipynb
  docs/source/tutorials/tutorial05.ipynb
  docs/source/tutorials/tutorial06.ipynb
  docs/source/tutorials/tutorial07.ipynb
  docs/source/tutorials/tutorial08.ipynb
  docs/source/tutorials/tutorial09.ipynb
  docs/source/tutorials/tutorial10.ipynb
  tutorials/README.md
  tutorials/application-example/energy_hospital_load.ipynb
  tutorials/application-example/energy_solar_pv.ipynb
  tutorials/feature-use/Live_plot_during_training.ipynb
  tutorials/feature-use/autoregression_yosemite_temps.ipynb
  tutorials/feature-use/collect_predictions.ipynb
  tutorials/feature-use/conditional_seasonality_peyton.ipynb
  tutorials/feature-use/events_holidays_peyton_manning.ipynb
  tutorials/feature-use/global_local_modeling.ipynb
  tutorials/feature-use/global_modeling.ipynb
  tutorials/feature-use/lagged_covariates_energy_ercot.ipynb
  tutorials/feature-use/migration_from_prophet.ipynb
  tutorials/feature-use/network_architecture_visualization.ipynb
  tutorials/feature-use/plotly.ipynb
  tutorials/feature-use/prophet_to_torch_prophet.ipynb
  tutorials/feature-use/season_multiplicative_air_travel.ipynb
  tutorials/feature-use/sparse_autoregression_yosemite_temps.ipynb
  tutorials/feature-use/sub_daily_data_yosemite_temps.ipynb
  tutorials/feature-use/test_and_crossvalidate.ipynb
  tutorials/feature-use/trend_peyton_manning.ipynb
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
  tutorials/feature-use/uncertainty_quantification.ipynb
  tutorials/feature-use/uncertainty_quantile_regression.ipynb
Labels: docs, status: in development

#1305 [minor] Update dependencies to latest versions
  poetry.lock
Labels: status: ready

#1262 [refactor] Uncertainty streamline naming
  docs/source/how-to-guides/feature-guides/uncertainty_quantification.ipynb
  docs/source/tutorials/tutorial08.ipynb
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_forecast_plotly.py
  neuralprophet/uncertainty.py
  tests/test_plotting.py
  tests/test_uncertainty.py
Labels: status: needs review
