Repository ourownstory/neural_prophet, pull requests merged in 2023-01, with the labels that each got.

#1074 Uncertainty: Conformal Prediction V1.1 - add Conformal class to conformal_prediction.py and rename file to conformal.py
  neuralprophet/conformal.py
  neuralprophet/conformal_prediction.py
  neuralprophet/forecaster.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: uncertainty, status: ready, refactoring, P2

#1096 [Bug-fix] Enable test_plot_conformal_prediction with auto-regression on plot_latest_forecast
  neuralprophet/utils.py
Labels: status: needs review

#1100 [Bug-fix] Enable holidays when using global/glocal modeling
  neuralprophet/time_dataset.py
Labels: status: needs review

#1109 [Bug-fix] Refactor warning about global normalization to forecaster.py
  neuralprophet/forecaster.py
  neuralprophet/time_net.py
Labels: bug, status: needs review

#1073 Uncertainty: Conformal Prediction V1.1 - extend to multiple forecast steps instead of only a single forecast step
  neuralprophet/conformal.py
  neuralprophet/forecaster.py
  neuralprophet/plot_forecast_matplotlib.py
  neuralprophet/plot_forecast_plotly.py
  tests/test_plotting.py
  tutorials/feature-use/uncertainty_conformal_prediction.ipynb
Labels: enhancement, uncertainty, status: needs review, P2

#1067 [enhancement] Add conditional seasonality as a new feature
  neuralprophet/configure.py
  neuralprophet/df_utils.py
  neuralprophet/forecaster.py
  neuralprophet/time_dataset.py
  tests/test_integration.py
Labels: enhancement, status: needs review

#1119 Fix ipython version for plotly-resampler
  requirements/base.txt
Labels: bug, plotting

#1114 Deactivate plotly resampler for static image export
  tests/test_model_performance.py
Labels: bug, status: needs review

#1091 Created narratives and simplified code for quantile regression tutorial material
  tutorials/feature-use/uncertainty_quantile_regression.ipynb
Labels: uncertainty, status: needs review, P2

#1121 Typing improvements
  .github/workflows/linters.yml
  neuralprophet/df_utils.py
  neuralprophet/forecaster.py
  neuralprophet/hdays.py
  neuralprophet/logger.py
  neuralprophet/time_net.py
  neuralprophet/utils.py
  pyproject.toml
Labels: status: ready, refactoring

#1123 [refactor] create dict for events or regressors
  neuralprophet/df_utils.py
Labels: status: ready, refactoring

#1124 Typing conformal prediction
  neuralprophet/conformal.py
  pyproject.toml
Labels: status: ready, refactoring

#1078 Trend modularization
  neuralprophet/components/README.md
  neuralprophet/components/__init__.py
  neuralprophet/components/base.py
  neuralprophet/components/router.py
  neuralprophet/components/trend/__init__.py
  neuralprophet/components/trend/linear.py
  neuralprophet/components/trend/piecewise_linear.py
  neuralprophet/components/trend/static.py
  neuralprophet/components/trend/trend.py
  neuralprophet/df_utils.py
  neuralprophet/plot_model_parameters_matplotlib.py
  neuralprophet/plot_model_parameters_plotly.py
  neuralprophet/time_net.py
  neuralprophet/utils_torch.py
  tests/test_integration.py
Labels: status: ready, modularity

#1072 [refactor] Extract holiday getter helper to single function
  neuralprophet/hdays_utils.py
  neuralprophet/time_dataset.py
  neuralprophet/utils.py
  tests/test_utils.py
Labels: status: ready, refactoring
